# Generated by Django 2.1.2 on 2018-10-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nap', '0004_auto_20181014_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='user',
        ),
    ]
